stages:
  - build
  - deploy

variables:
  BOT_REPO: 036291388481.dkr.ecr.eu-central-1.amazonaws.com/remind_me_bot
  TAG: $CI_COMMIT_TAG

before_script:
  - eval $(aws ecr get-login --no-include-email --region=$AWS_REGION)

build_image:
  stage: build
  script: 
    - docker build -t $BOT_REPO:$TAG
    - docker push $BOT_REPO:$TAG
  only: 
    - tags
  

deploy:
  stage: deploy
  script: 
    - export $TAG; docker stack deploy --with-registry-auth -c stack.yml remind_bot
  only: 
    - tags