stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_COMMIT_TAG

before_script:
  - eval $(/usr/bin/aws ecr get-login --no-include-email --region=$AWS_REGION)

build_image:
  stage: build
  script: 
    - echo $CI_COMMIT_TAG > VERSION
    - docker build -t $BOT_REPO:$IMAGE_TAG .
    - docker push $BOT_REPO:$IMAGE_TAG
  only: 
    - tags
  

deploy:
  stage: deploy
  script: 
    - export TAG=$IMAGE_TAG; docker stack deploy --with-registry-auth -c stack.yml remind_bot
  only: 
    - tags