version: '3.7'

services:
  db:
    image: postgres:11
    restart: on-failure
    container_name: reminder_db
    environment:
      POSTGRES_USER: reminder
      POSTGRES_PASSWORD: reminder_pass
      POSTGRES_DB: reminds_db
    ports:
      - '5432:5432'
    volumes:
      - ./.postgres:/var/lib/postgresql/data
